*** Starting uWSGI 2.0.21 (64bit) on [Wed May 24 00:27:56 2023] ***
compiled with version: 11.2.0 on 28 March 2023 07:30:06
os: Linux-5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020
nodename: CrServer
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /home/caryz/QuestionPlanet
writing pidfile to /home/caryz/QuestionPlanet/uwsgi.pid
detected binary path: /home/caryz/miniconda3/envs/django/bin/uwsgi
chdir() to /home/caryz/QuestionPlanet
your processes number limit is 14775
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:5000).
bind(): Address already in use [core/socket.c line 769]
*** Starting uWSGI 2.0.21 (64bit) on [Wed May 24 01:10:03 2023] ***
compiled with version: 11.2.0 on 28 March 2023 07:30:06
os: Linux-5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020
nodename: CrServer
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /home/caryz/QuestionPlanet
writing pidfile to /home/caryz/QuestionPlanet/uwsgi.pid
detected binary path: /home/caryz/miniconda3/envs/django/bin/uwsgi
chdir() to /home/caryz/QuestionPlanet
your processes number limit is 14775
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:5678 fd 3
Python version: 3.8.16 (default, Mar  2 2023, 03:21:46)  [GCC 11.2.0]
Set PythonHome to /home/caryz/miniconda3/envs/django
Python main interpreter initialized at 0x1c1d830
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1856286 bytes (1812 KB) for 16 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1c1d830 pid: 342446 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 342446)
spawned uWSGI worker 1 (pid: 342448, cores: 2)
spawned uWSGI worker 2 (pid: 342450, cores: 2)
spawned uWSGI worker 3 (pid: 342451, cores: 2)
spawned uWSGI worker 4 (pid: 342452, cores: 2)
spawned uWSGI worker 5 (pid: 342453, cores: 2)
spawned uWSGI worker 6 (pid: 342456, cores: 2)
spawned uWSGI worker 7 (pid: 342457, cores: 2)
spawned uWSGI worker 8 (pid: 342461, cores: 2)
Invalid HTTP_HOST header: '182.92.102.246:1145'. You may need to add '182.92.102.246' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/caryz/miniconda3/envs/django/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/caryz/miniconda3/envs/django/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/caryz/miniconda3/envs/django/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/caryz/miniconda3/envs/django/lib/python3.8/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '182.92.102.246:1145'. You may need to add '182.92.102.246' to ALLOWED_HOSTS.
Bad Request: /api/user/user_register
[pid: 342453|app: 0|req: 1/1] 106.39.42.236 () {40 vars in 584 bytes} [Tue May 23 17:11:24 2023] POST /api/user/user_register => generated 58570 bytes in 132 msecs (HTTP/1.1 400) 4 headers in 172 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '182.92.102.246:1145'. You may need to add '182.92.102.246' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/caryz/miniconda3/envs/django/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/caryz/miniconda3/envs/django/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/caryz/miniconda3/envs/django/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/caryz/miniconda3/envs/django/lib/python3.8/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '182.92.102.246:1145'. You may need to add '182.92.102.246' to ALLOWED_HOSTS.
Bad Request: /api/user/user_register
[pid: 342461|app: 0|req: 1/2] 106.39.42.236 () {40 vars in 584 bytes} [Tue May 23 17:14:45 2023] POST /api/user/user_register => generated 58570 bytes in 107 msecs (HTTP/1.1 400) 4 headers in 172 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.21 (64bit) on [Wed May 24 01:29:31 2023] ***
compiled with version: 11.2.0 on 28 March 2023 07:30:06
os: Linux-5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020
nodename: CrServer
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /home/caryz/QuestionPlanet
writing pidfile to /home/caryz/QuestionPlanet/uwsgi.pid
detected binary path: /home/caryz/miniconda3/envs/django/bin/uwsgi
chdir() to /home/caryz/QuestionPlanet
your processes number limit is 14775
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:5678).
bind(): Address already in use [core/socket.c line 769]
Invalid HTTP_HOST header: '182.92.102.246:1145'. You may need to add '182.92.102.246' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/caryz/miniconda3/envs/django/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/caryz/miniconda3/envs/django/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/caryz/miniconda3/envs/django/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/caryz/miniconda3/envs/django/lib/python3.8/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '182.92.102.246:1145'. You may need to add '182.92.102.246' to ALLOWED_HOSTS.
Bad Request: /api/user/user_register
[pid: 342461|app: 0|req: 2/3] 106.39.42.236 () {40 vars in 584 bytes} [Tue May 23 17:30:22 2023] POST /api/user/user_register => generated 58570 bytes in 20 msecs (HTTP/1.1 400) 4 headers in 172 bytes (1 switches on core 1)
Invalid HTTP_HOST header: '182.92.102.246:1145'. You may need to add '182.92.102.246' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/caryz/miniconda3/envs/django/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/caryz/miniconda3/envs/django/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/caryz/miniconda3/envs/django/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/caryz/miniconda3/envs/django/lib/python3.8/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '182.92.102.246:1145'. You may need to add '182.92.102.246' to ALLOWED_HOSTS.
Bad Request: /api/user/user_register
[pid: 342461|app: 0|req: 3/4] 106.39.42.236 () {40 vars in 584 bytes} [Tue May 23 17:44:18 2023] POST /api/user/user_register => generated 58570 bytes in 32 msecs (HTTP/1.1 400) 4 headers in 172 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '182.92.102.246:1145'. You may need to add '182.92.102.246' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/caryz/miniconda3/envs/django/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/caryz/miniconda3/envs/django/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/caryz/miniconda3/envs/django/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/caryz/miniconda3/envs/django/lib/python3.8/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '182.92.102.246:1145'. You may need to add '182.92.102.246' to ALLOWED_HOSTS.
Bad Request: /api/user/user_register
[pid: 342461|app: 0|req: 4/5] 106.39.42.236 () {40 vars in 584 bytes} [Tue May 23 17:44:44 2023] POST /api/user/user_register => generated 58570 bytes in 29 msecs (HTTP/1.1 400) 4 headers in 172 bytes (1 switches on core 1)
Wed May 24 02:53:54 2023 - uWSGI worker 8 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.21 (64bit) on [Wed May 24 11:01:03 2023] ***
compiled with version: 11.2.0 on 28 March 2023 07:30:06
os: Linux-5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020
nodename: CrServer
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /home/caryz/QuestionPlanet
writing pidfile to /home/caryz/QuestionPlanet/uwsgi.pid
detected binary path: /home/caryz/miniconda3/envs/django/bin/uwsgi
chdir() to /home/caryz/QuestionPlanet
your processes number limit is 14775
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:5678 fd 3
Python version: 3.8.16 (default, Mar  2 2023, 03:21:46)  [GCC 11.2.0]
Set PythonHome to /home/caryz/miniconda3/envs/django
Python main interpreter initialized at 0x2368830
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1856286 bytes (1812 KB) for 16 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x2368830 pid: 344163 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 344163)
spawned uWSGI worker 1 (pid: 344165, cores: 2)
spawned uWSGI worker 2 (pid: 344167, cores: 2)
spawned uWSGI worker 3 (pid: 344168, cores: 2)
spawned uWSGI worker 4 (pid: 344170, cores: 2)
spawned uWSGI worker 5 (pid: 344171, cores: 2)
spawned uWSGI worker 6 (pid: 344173, cores: 2)
spawned uWSGI worker 7 (pid: 344175, cores: 2)
spawned uWSGI worker 8 (pid: 344176, cores: 2)
[pid: 344175|app: 0|req: 1/1] 106.39.42.236 () {40 vars in 584 bytes} [Wed May 24 03:06:01 2023] POST /api/user/user_register => generated 62 bytes in 105 msecs (HTTP/1.1 200) 7 headers in 212 bytes (1 switches on core 0)
